"""add default user role

Revision ID: 54b9a5c99283
Revises: dda7c26ffe41
Create Date: 2024-04-01 05:35:56.485050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54b9a5c99283'
down_revision: Union[str, None] = 'dda7c26ffe41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('roles', 'role')
    op.add_column('users', sa.Column('role', sa.Integer(), nullable=True))
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role'], ['id'])
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_role_id_fkey', 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'role')
    op.add_column('roles', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('roles', 'name')
    # ### end Alembic commands ###
