"""roles and permision many to many

Revision ID: 67af592dd615
Revises: d99218393303
Create Date: 2024-04-03 02:47:49.551968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67af592dd615'
down_revision: Union[str, None] = 'd99218393303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('permissions_role_id_fkey', 'permissions', type_='foreignkey')
    op.drop_column('permissions', 'role_id')
    op.drop_constraint('roles_permission_id_fkey', 'roles', type_='foreignkey')
    op.drop_column('roles', 'permission_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('roles_permission_id_fkey', 'roles', 'permissions', ['permission_id'], ['id'])
    op.add_column('permissions', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('permissions_role_id_fkey', 'permissions', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
