"""Added test table

Revision ID: 8775a9bc0f15
Revises: 
Create Date: 2024-03-19 10:47:36.938825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8775a9bc0f15'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('hero')
    op.create_unique_constraint(None, 'books', ['isbn_number'])
    op.create_foreign_key(None, 'books', 'genre', ['genre_id'], ['id'])
    op.create_unique_constraint(None, 'magazines', ['issn_number'])
    op.create_foreign_key(None, 'magazines', 'genre', ['genre_id'], ['id'])
    op.create_foreign_key(None, 'records', 'genre', ['genre_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.drop_constraint(None, 'magazines', type_='foreignkey')
    op.drop_constraint(None, 'magazines', type_='unique')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint(None, 'books', type_='unique')
    op.create_table('hero',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='hero_pkey')
    )
    op.drop_table('auto')
    # ### end Alembic commands ###
