"""inital

Revision ID: 9f228b6d4954
Revises: 
Create Date: 2024-03-29 05:51:21.301571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f228b6d4954'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'books', ['isbn_number'])
    op.create_unique_constraint(None, 'magazines', ['issn_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'magazines', type_='unique')
    op.drop_constraint(None, 'books', type_='unique')
    # ### end Alembic commands ###
